matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      language: node_js
      node_js: "10"
      addons:
        apt:
          packages:
            - libx11-dev
            - libxkbfile-dev
            - libxtst-dev
            - libpng++-dev
            - make
            - rpm
    - os: windows
      language: node_js
      node_js: "10"
    - os: linux
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=lint
      addons:
        apt:
          packages:
            - libx11-dev
            - libxkbfile-dev
            - libxtst-dev
            - libpng++-dev
            - make
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=test

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script: ./script/travis.sh

notifications:
  email: false
