matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=dist
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=dist
      addons:
        apt:
          packages:
            - libx11-dev
            - libxkbfile-dev
            - libxtst-dev
            - libpng++-dev
            - make
            - rpm
    - os: linux
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=dist-windows
      addons:
        apt:
          packages:
            - libx11-dev
            - libxkbfile-dev
            - libxtst-dev
            - libpng++-dev
            - make
            - rpm
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=dist
    - os: linux
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=lint
      addons:
        apt:
          packages:
            - libx11-dev
            - libxkbfile-dev
            - libxtst-dev
            - libpng++-dev
            - make
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "10"
      env:
        - YARN_COMMAND=test

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - |
    if [ "$YARN_COMMAND" == "dist-windows" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile --ignore-engines && yarn dist --win"
    else
      yarn --link-duplicates --pure-lockfile --ignore-engines; yarn $YARN_COMMAND
    fi

notifications:
  email: false
